#!/bin/bash
# ─────────────────────────────────────────────────────────────────
#  Mosaic — smoke tests
#
#  Drives the demo at examples/mosaic-fs-demo/ through the full
#  pipeline, then curls every route over HTTP/2 cleartext to verify
#  end-to-end behaviour.
#
#  Requires:
#    - amc (path passed as arg, or autodetected via PATH)
#    - amc runtime headers (auto-detected, or set AMC_RUNTIME)
#    - libgc-dev, libnghttp2-dev, libcurl
#    - amalgame-web + amalgame-net-http installed in
#      ~/.amalgame/packages/ (use `amc package add web@v0.2.1` +
#      `amc package add net-http@v0.2.0` first)
# ─────────────────────────────────────────────────────────────────

set -e

PKG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEMO_DIR="$PKG_DIR/examples/mosaic-fs-demo"

AMC=""
if [ -n "${1:-}" ]; then AMC="$1"
elif command -v amc >/dev/null 2>&1; then AMC="$(command -v amc)"
elif [ -x "$HOME/.local/bin/amc" ];   then AMC="$HOME/.local/bin/amc"
elif [ -x "$HOME/.amalgame/bin/amc" ]; then AMC="$HOME/.amalgame/bin/amc"
fi
[ -z "$AMC" ] || [ ! -x "$AMC" ] && { echo "error: amc not found"; exit 2; }

export AMC

if [ -t 1 ]; then
    GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
else
    GREEN=''; RED=''; NC=''
fi
PASS=0
FAIL=0
check() {
    local name="$1" got="$2" want="$3"
    if [ "$got" = "$want" ]; then
        echo -e "  ${GREEN}PASS${NC}  $name"
        PASS=$((PASS+1))
    else
        echo -e "  ${RED}FAIL${NC}  $name  (got '$got', want '$want')"
        FAIL=$((FAIL+1))
    fi
}

# Need a lock pointing at installed packages. Synthesize from the
# user's package cache so we don't burn into a hardcoded rev.
WEB_DIR=$(find "$HOME/.amalgame/packages/github.com/amalgame-lang/amalgame-web" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort | tail -1)
HTTP_DIR=$(find "$HOME/.amalgame/packages/github.com/amalgame-lang/amalgame-net-http" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | sort | tail -1)
if [ -z "$WEB_DIR" ] || [ -z "$HTTP_DIR" ]; then
    echo "error: install amalgame-web + amalgame-net-http first via amc package add"
    exit 2
fi
WEB_TAG_REV="$(basename "$WEB_DIR")"
HTTP_TAG_REV="$(basename "$HTTP_DIR")"
WEB_TAG="${WEB_TAG_REV%_*}"
WEB_REV="${WEB_TAG_REV##*_}"
HTTP_TAG="${HTTP_TAG_REV%_*}"
HTTP_REV="${HTTP_TAG_REV##*_}"

cat > "$DEMO_DIR/amalgame.lock" <<EOF
# amalgame.lock — generated by tests/run_tests.sh

[[package]]
name = "web"
git  = "github.com/amalgame-lang/amalgame-web"
tag  = "$WEB_TAG"
rev  = "$WEB_REV"

[[package]]
name = "net-http"
git  = "github.com/amalgame-lang/amalgame-net-http"
tag  = "$HTTP_TAG"
rev  = "$HTTP_REV"
EOF

cd "$DEMO_DIR"
echo "── Build pipeline ──"

# Boot server on a unique port to avoid collisions with anything
# on :3000 (the demo's natural port). Patch server.am in a copy +
# restore so the user's source tree never gets mutated. Earlier
# versions of this script `sed -i`'d the demo source in place and
# left a 13099-port leak in the released v0.1.0 tag — fixed in
# v0.1.2.
PORT=13099
cp server.am server.am.orig
trap 'mv -f server.am.orig server.am 2>/dev/null || true' EXIT
# Match either Http1.Serve or Http2.Serve — the demo defaults to
# Http1 since mosaic v0.1.3 but we keep the test resilient to swaps.
sed -i -E "s/(Http[12]\.Serve)\([0-9]+/\1($PORT/" server.am

"$PKG_DIR/tools/mosaic-build.sh" > /tmp/mosaic-build.log 2>&1
if [ ! -x ./server ]; then
    echo -e "  ${RED}FAIL${NC} (build) — last 20 lines of log:"
    tail -20 /tmp/mosaic-build.log
    exit 1
fi
echo -e "  ${GREEN}PASS${NC} (./server built)"

./server > /tmp/mosaic-server.log 2>&1 &
PID=$!
sleep 0.5
trap "kill $PID 2>/dev/null || true; wait $PID 2>/dev/null || true; mv -f server.am.orig server.am 2>/dev/null || true" EXIT

echo "── Routes (HTTP/1.1) ──"
H=":$PORT"

# The demo now defaults to Http1.Serve (browser-friendly). Curl
# without --http2-prior-knowledge will speak plain HTTP/1.1, and
# %{http_version} comes back as "1.1".
check "/ → 200"            "$(curl -s http://localhost$H/         -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "/about → 200"       "$(curl -s http://localhost$H/about    -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "/users/42 → 200"    "$(curl -s http://localhost$H/users/42 -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "/users/:id body"    "$(curl -s http://localhost$H/users/42 | tr -d '\n')" "User #42"
check "/api/info → 200"    "$(curl -s http://localhost$H/api/info -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "POST /api/info 201" "$(curl -s -X POST http://localhost$H/api/info -o /dev/null -w '%{http_version} %{http_code}')" "1.1 201"
check "/nope → 404"        "$(curl -s http://localhost$H/nope     -o /dev/null -w '%{http_version} %{http_code}')" "1.1 404"

echo ""
echo "  $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
