#!/bin/bash
# ─────────────────────────────────────────────────────────────────
#  Mosaic — smoke tests
#
#  Drives the demo at examples/mosaic-fs-demo/ through the full
#  pipeline, then curls every route over HTTP/2 cleartext to verify
#  end-to-end behaviour.
#
#  Requires:
#    - amc (path passed as arg, or autodetected via PATH)
#    - amc runtime headers (auto-detected, or set AMC_RUNTIME)
#    - libgc-dev, libnghttp2-dev, libcurl
#    - amalgame-web + amalgame-net-http installed in
#      ~/.amalgame/packages/ (use `amc package add web@v0.2.1` +
#      `amc package add net-http@v0.2.0` first)
# ─────────────────────────────────────────────────────────────────

set -e

PKG_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEMO_DIR="$PKG_DIR/examples/mosaic-fs-demo"

AMC=""
if [ -n "${1:-}" ]; then AMC="$1"
elif command -v amc >/dev/null 2>&1; then AMC="$(command -v amc)"
elif [ -x "$HOME/.local/bin/amc" ];   then AMC="$HOME/.local/bin/amc"
elif [ -x "$HOME/.amalgame/bin/amc" ]; then AMC="$HOME/.amalgame/bin/amc"
fi
[ -z "$AMC" ] || [ ! -x "$AMC" ] && { echo "error: amc not found"; exit 2; }

export AMC

if [ -t 1 ]; then
    GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
else
    GREEN=''; RED=''; NC=''
fi
PASS=0
FAIL=0
check() {
    local name="$1" got="$2" want="$3"
    if [ "$got" = "$want" ]; then
        echo -e "  ${GREEN}PASS${NC}  $name"
        PASS=$((PASS+1))
    else
        echo -e "  ${RED}FAIL${NC}  $name  (got '$got', want '$want')"
        FAIL=$((FAIL+1))
    fi
}

cd "$DEMO_DIR"

# Snapshot the demo's source-tree-tracked files so the test
# never leaves the working copy dirty:
#   server.am       — patched for the unique test port (sed below)
#   amalgame.toml   — `amc package add web` below inflates the
#                      [dependencies] table with long-form entries
#                      for every transitive; we restore the
#                      short-form checked-in version on exit.
#   amalgame.lock   — auto-generated by amc, gitignored, but tidy
#                      anyway.
cp server.am server.am.orig
cp amalgame.toml amalgame.toml.orig
trap '
    mv -f server.am.orig server.am 2>/dev/null || true
    mv -f amalgame.toml.orig amalgame.toml 2>/dev/null || true
    rm -f amalgame.lock 2>/dev/null || true
' EXIT

# v0.6.0: amc v0.8.49+'s `amc package add web` writes a complete
# multi-entry amalgame.lock (web + every transitive dep) AND
# updates amalgame.toml with long-form `[dependencies.X] git=...
# tag=...` entries for every transitive. We just need to make
# sure the cache is hydrated; amc handles the lock + toml from
# there. (Pre-v0.8.49, this script manually synthesized a
# 2-entry lock — which worked when web's dep graph was tiny but
# broke once Threading/Logging/Async/etc. entered the picture.)
echo "── Hydrate package cache ──"
if ! "$AMC" package add web > /tmp/mosaic-amc-add.log 2>&1; then
    echo -e "  ${RED}FAIL${NC} (amc package add web) — last 30 lines of log:"
    tail -30 /tmp/mosaic-amc-add.log
    exit 1
fi
PKG_COUNT=$(grep -c '^\[\[package\]\]' amalgame.lock 2>/dev/null || echo "?")
echo -e "  ${GREEN}PASS${NC} (amc package add web — ${PKG_COUNT} packages locked)"

echo "── Build pipeline ──"

# Boot server on a unique port to avoid collisions with anything
# on :3000 (the demo's natural port).
PORT=13099
# Match the entry-point Serve call. Patterns we cover, in order
# of first introduction:
#   - Http1.Serve(NNN)/Http2.Serve(NNN)  pre-v0.6 demos
#   - app.Serve(NNN)                     v0.6 (WebApp wrapper)
sed -i -E \
    -e "s/(Http[12]\.Serve)\([0-9]+/\1($PORT/" \
    -e "s/(app\.Serve)\([0-9]+/\1($PORT/" \
    server.am

# Disable set -e around mosaic-build.sh so the `[ ! -x ./server ]`
# diagnostic + log dump actually run on a failed build (otherwise
# set -e exits silently with whatever code mosaic-build.sh returned).
set +e
"$PKG_DIR/tools/mosaic-build.sh" > /tmp/mosaic-build.log 2>&1
BUILD_RC=$?
set -e
if [ "$BUILD_RC" -ne 0 ] || [ ! -x ./server ]; then
    echo -e "  ${RED}FAIL${NC} (build, exit=$BUILD_RC) — last 30 lines of log:"
    tail -30 /tmp/mosaic-build.log
    exit 1
fi
echo -e "  ${GREEN}PASS${NC} (./server built)"

./server > /tmp/mosaic-server.log 2>&1 &
PID=$!
sleep 0.5
trap "kill $PID 2>/dev/null || true; wait $PID 2>/dev/null || true; mv -f server.am.orig server.am 2>/dev/null || true" EXIT

echo "── Routes (HTTP/1.1) ──"
H=":$PORT"

# The demo now defaults to Http1.Serve (browser-friendly). Curl
# without --http2-prior-knowledge will speak plain HTTP/1.1, and
# %{http_version} comes back as "1.1".
check "/ → 200"            "$(curl -s http://localhost$H/         -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "/about → 200"       "$(curl -s http://localhost$H/about    -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "/users/42 → 200"    "$(curl -s http://localhost$H/users/42 -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "/users/:id body"    "$(curl -s http://localhost$H/users/42 | tr -d '\n')" "User #42"
check "/api/info → 200"    "$(curl -s http://localhost$H/api/info -o /dev/null -w '%{http_version} %{http_code}')" "1.1 200"
check "POST /api/info 201" "$(curl -s -X POST http://localhost$H/api/info -o /dev/null -w '%{http_version} %{http_code}')" "1.1 201"
check "/nope → 404"        "$(curl -s http://localhost$H/nope     -o /dev/null -w '%{http_version} %{http_code}')" "1.1 404"

# v0.6.0 — Static / public/ auto-pairing
echo "── Static (public/) ──"
check "/style.css → 200"   "$(curl -s http://localhost$H/style.css  -o /dev/null -w '%{http_code}')" "200"
check "/style.css MIME"    "$(curl -sI http://localhost$H/style.css | grep -i '^content-type:' | head -c 30 | tr -d '\r')" "Content-Type: text/css; charse"
check "/favicon.ico → 200" "$(curl -s http://localhost$H/favicon.ico -o /dev/null -w '%{http_code}')" "200"
# Binary-safe: favicon contains NUL bytes — wire bytes must match
# the on-disk file byte-for-byte, not strlen-truncate at first NUL.
FAV_DISK=$(stat -c%s "$DEMO_DIR/public/favicon.ico")
FAV_WIRE=$(curl -s http://localhost$H/favicon.ico | wc -c)
check "/favicon.ico binary-safe" "$FAV_WIRE" "$FAV_DISK"
ETAG=$(curl -sI http://localhost$H/style.css | grep -i '^etag:' | sed -E 's/^etag:[[:space:]]*//I; s/\r$//')
check "/style.css emits ETag"    "$([ -n "$ETAG" ] && echo yes || echo no)" "yes"
check "If-None-Match → 304"      "$(curl -s -H "If-None-Match: $ETAG" http://localhost$H/style.css -o /dev/null -w '%{http_code}')" "304"
check "/no-such.css → 404"       "$(curl -s http://localhost$H/no-such.css -o /dev/null -w '%{http_code}')" "404"

echo ""
echo "  $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
