#!/bin/bash
# ─────────────────────────────────────────────────────────────────
#  mosaic-new.sh — scaffold a new Mosaic application
#
#  Drops a working skeleton in `<dir>` (default: cwd) and runs
#  `amc package add` to install the runtime deps so the very next
#  command — `mosaic dev` — produces a serving binary.
#
#  Scaffold contents:
#    amalgame.toml         — package manifest with web + net-http
#                              + crypto in [dependencies] (amc >=
#                              0.8.39 pulls them transitively).
#    server.am             — Main using WebApp + filesystem routes.
#    app/index.am          — GET / "Hello Mosaic" example.
#    app/api/info.am       — GET /api/info JSON example.
#    README.md             — quickstart blurb.
#    .gitignore            — server binary, generated _routes.am,
#                              certs/, build artifacts.
#
#  Usage:
#    mosaic new my-site
#    mosaic new --skip-install my-site     # don't auto-run amc package add
#    mosaic new                            # scaffold in cwd (refuses if
#                                            existing amalgame.toml found)
# ─────────────────────────────────────────────────────────────────

set -euo pipefail

if [ -t 1 ]; then
    GREEN='\033[0;32m'
    YELLOW='\033[0;33m'
    CYAN='\033[0;36m'
    RED='\033[0;31m'
    NC='\033[0m'
else
    GREEN=''; YELLOW=''; CYAN=''; RED=''; NC=''
fi

usage() {
    cat <<EOF
mosaic-new — scaffold a new Mosaic application

Usage:
  mosaic-new [OPTIONS] [<dir>]

Options:
  --skip-install    Skip the auto-run of \`amc package add web\` after
                    scaffolding.  Use when you want to inspect the
                    manifest before pulling deps.
  --name NAME       Override the package name in amalgame.toml
                    (default: basename of <dir>).
  -h, --help        Show this help.

Examples:
  mosaic-new my-site
  mosaic-new                       # scaffold in cwd
  mosaic-new --skip-install my-site
EOF
}

SKIP_INSTALL=0
TARGET=""
NAME_OVERRIDE=""
while [ $# -gt 0 ]; do
    case "$1" in
        -h|--help)         usage; exit 0 ;;
        --skip-install)    SKIP_INSTALL=1; shift ;;
        --name)            NAME_OVERRIDE="$2"; shift 2 ;;
        -*)                echo "mosaic new: unknown flag $1" >&2; usage; exit 2 ;;
        *)
            if [ -n "$TARGET" ]; then
                echo "mosaic new: only one <dir> argument allowed" >&2
                exit 2
            fi
            TARGET="$1"; shift
            ;;
    esac
done

if [ -z "$TARGET" ]; then
    TARGET="."
fi

# Resolve absolute path and decide name.
if [ "$TARGET" != "." ]; then
    if [ -e "$TARGET" ] && [ ! -d "$TARGET" ]; then
        echo -e "${RED}mosaic new: $TARGET exists and is not a directory${NC}" >&2
        exit 1
    fi
    mkdir -p "$TARGET"
fi
TARGET_ABS="$(cd "$TARGET" && pwd)"
NAME="${NAME_OVERRIDE:-$(basename "$TARGET_ABS")}"

if [ -e "$TARGET_ABS/amalgame.toml" ]; then
    echo -e "${RED}mosaic new: $TARGET_ABS/amalgame.toml already exists — refusing to overwrite${NC}" >&2
    echo "  pass a different <dir>, or remove the existing manifest." >&2
    exit 1
fi

echo -e "${CYAN}→${NC} scaffolding ${GREEN}$NAME${NC} in $TARGET_ABS"
mkdir -p "$TARGET_ABS/app/api"

# ── amalgame.toml ────────────────────────────────────────────────
cat > "$TARGET_ABS/amalgame.toml" <<EOF
# Mosaic application — generated by \`mosaic new\` ($(date +%Y-%m-%d)).
#
# Deps are pulled transitively by amc v0.8.39+ via [dependencies].
# Older amc: run \`amc package add web net-http tls crypto\` manually.

[package]
name        = "$NAME"
version     = "0.1.0"
license     = "Apache-2.0"
description = "A Mosaic application."
entry       = "server.am"

[dependencies]
amalgame-web      = ">=0.11.3"
amalgame-net-http = ">=0.7.1"
amalgame-tls      = ">=0.3.1"
amalgame-crypto   = ">=0.3.0"
EOF

# ── .gitignore ───────────────────────────────────────────────────
cat > "$TARGET_ABS/.gitignore" <<'EOF'
# Build artifacts
/server
/*.c
/_routes.am
/.amalgame-cache/

# Runtime data
/certs/
/data/
/sessions/

# Editor cruft
*.swp
*~
.DS_Store
EOF

# ── server.am ────────────────────────────────────────────────────
cat > "$TARGET_ABS/server.am" <<EOF
// $NAME — Mosaic entry point.
//
// Generated by \`mosaic new\`.  Mosaic regenerates _routes.am from
// the contents of app/ before each build (see \`mosaic dev\` /
// \`mosaic build\`).  Each app/<path>.am file becomes a route; this
// file just wires the router into a WebApp and starts an HTTP
// listener.

namespace App

import Amalgame.Collections
import Amalgame.Web
import Amalgame.Net.Http

public class Program {
    public static int Main(string[] args) {
        let app = new WebApp()
        Routes.Register(app.Router)

        Console.WriteLine("$NAME — listening on http://localhost:3000")
        Console.WriteLine("  routes: " + String_FromInt(app.Router.Routes.Count()))
        Console.WriteLine("")

        return app.Serve(3000)
    }
}
EOF

# ── app/index.am ─────────────────────────────────────────────────
cat > "$TARGET_ABS/app/index.am" <<EOF
// app/index.am  →  GET /

import Amalgame.Web

public class Page {
    public static HttpResponse GET(ctx: WebContext) {
        let html: string = "<!doctype html><html><head>" +
            "<title>$NAME</title>" +
            "<style>body{font-family:system-ui,sans-serif;max-width:42em;margin:3em auto}</style>" +
            "</head><body>" +
            "<h1>$NAME</h1>" +
            "<p>Edit <code>app/index.am</code> and re-run " +
            "<code>mosaic dev</code> to see the change.</p>" +
            "<p>JSON example: <a href=\"/api/info\">/api/info</a></p>" +
            "</body></html>"
        return HttpResponse.New().Html(html)
    }
}
EOF

# ── app/api/info.am ──────────────────────────────────────────────
cat > "$TARGET_ABS/app/api/info.am" <<EOF
// app/api/info.am  →  GET /api/info  (JSON)

import Amalgame.Web

public class Page {
    public static HttpResponse GET(ctx: WebContext) {
        let body: string = "{\"app\":\"$NAME\",\"version\":\"0.1.0\"}"
        return HttpResponse.New()
            .Header("content-type", "application/json")
            .Text(body)
    }
}
EOF

# ── README.md ────────────────────────────────────────────────────
cat > "$TARGET_ABS/README.md" <<EOF
# $NAME

A Mosaic application.

## Develop

\`\`\`sh
mosaic dev
\`\`\`

Hot reloads on every save under \`app/\` and \`server.am\`.  Open
[http://localhost:3000](http://localhost:3000) in your browser.

## Build for production

\`\`\`sh
mosaic build -o ./dist/server
./dist/server
\`\`\`

## Project layout

\`\`\`
$NAME/
├── amalgame.toml         # package manifest + transitive deps
├── server.am             # Main: routes → WebApp → HTTP listener
├── app/                  # Each file = a route
│   ├── index.am          # GET /
│   └── api/info.am       # GET /api/info
├── _routes.am            # ← regenerated from app/ by mosaic
└── server                # ← built binary
\`\`\`

Add files under \`app/\` to add routes:

  - \`app/users.am\` → \`/users\`
  - \`app/users/[id].am\` → \`/users/:id\`
  - \`app/blog/[...slug].am\` → \`/blog/*slug\`

Each file declares a \`public class Page\` with one method per HTTP
verb (\`GET\`, \`POST\`, \`PUT\`, \`DELETE\`, \`PATCH\`).

## Going to production

For HTTPS via Let's Encrypt, see the
[letsencrypt-site example](https://github.com/amalgame-lang/amalgame-tls/tree/main/examples/letsencrypt-site)
in amalgame-tls.
EOF

echo -e "${GREEN}✓${NC} scaffold ready: $TARGET_ABS"
echo "  amalgame.toml"
echo "  server.am"
echo "  app/index.am"
echo "  app/api/info.am"
echo "  README.md"
echo "  .gitignore"
echo ""

# ── Auto-install deps ────────────────────────────────────────────
if [ "$SKIP_INSTALL" -eq 1 ]; then
    echo -e "${YELLOW}→${NC} skipping \`amc package add\` (--skip-install)"
    echo ""
    echo "Next:"
    echo "  cd $TARGET_ABS"
    echo "  amc package add web net-http tls crypto    # or rely on amc v0.8.39+ transitive deps"
    echo "  mosaic dev"
    exit 0
fi

if ! command -v amc >/dev/null 2>&1; then
    echo -e "${YELLOW}!${NC} amc not on \$PATH — skipping auto-install."
    echo "  install amc from https://github.com/amalgame-lang/Amalgame/releases,"
    echo "  then \`cd $TARGET_ABS && amc package add web\`."
    exit 0
fi

echo -e "${CYAN}→${NC} installing deps (amc package add web)"
(cd "$TARGET_ABS" && amc package add web)

echo ""
echo -e "${GREEN}✓${NC} ready! next:"
echo "  cd $TARGET_ABS"
echo "  mosaic dev"
